### ISSUE TITLE
Tutorial: Link to pip documentation is incorrect

### ISSUE THREAD

**Issue by GadgetSteve** [rfk/pyenchant#102]
The link to the pip documentation in the tutorial section on installation appears as:

The easiest way to install PyEnchant is via `pip <<a href=”http://pip.readthedocs.org/en/latest/”>`_

and links to http://pythonhosted.org/pyenchant/tutorial.html#id25 - this is almost certainly not what was intended.

**Comment by GadgetSteve** [comment]
I have taken a look at the source for the tutorial and the looks to match the valid, documented, format for both rst2html and sphinx-doc _but possibly not for github_ but without knowing how the page is normally built I cannot reproduce the issue so cannot be sure of any fix.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
