### ISSUE TITLE
PyEnchant : Handle Internet Acronyms

### ISSUE THREAD

**Issue by gpadbidri** [rfk/pyenchant#106]
I want this library to handle Internet abbreviations. For Example : If a statement contains : "**FYI**, I need your pen." -> It should be interpreted as "**Just for your information**, I need your pen."

How can I do this with PyEnchant ? Can I add mappings in a custom words list (PWL) that way the FYI is replaced by Just for your information ?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
