### ISSUE TITLE
PWL and Suggest() do not work as expected

### ISSUE THREAD

**Issue by gpadbidri** [rfk/pyenchant#107]
I have my own set of words, hence I merged the English DIctionary with My Words List as follows : 
`d1 = enchant.DictWithPWL("en_US","include.txt")`

NOTE : Include.txt has the word "gauri"

Now when I say suggest me words for "gauri" as follows : 

`b = d2.suggest("gauri");`

I get the following Output : 

['Lauri', 'Gautier', 'Gaulish', 'gaudily', 'gauger', 'gauri']

**Ideally, I was expecting "gauri" to be ranked HIGHER and listed FIRST in the list.**

How do I achieve this ?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
