### ISSUE TITLE
Aspell and Store_replacement() related

### ISSUE THREAD

**Issue by gpadbidri** [rfk/pyenchant#108]
I am facing following issues : 

1. With store_replacement() I want to get "your" when I have the word "ur". Now by default, the first suggestion shows up as "Ur". How can I get my SET correct word to appear FIRST in the Suggestions for a misspelled word ? Is it possible and how ?

2. Ideally, these mappings would be stored in some dictionary file. Making my hardcoded list of word mappings via code is not possible. Where and how (format) can I paste these mappings in my PWL file (not sure, or some other place) so that suggestions work as if I have set misspelled words via store_replacement() API ?

3. Also, how can I identify words (eg : sooooooo = so) based on a REGEX for pattern matching ? Is it currently supported in PyEnchant ? If not, what can I do to enable this ? I dont mind committing it to github either.

Thanks !

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
