### ISSUE TITLE
genitive apostrophe s is detected as one word

### ISSUE THREAD

**Issue by codingjoe** [rfk/pyenchant#110]
6ff36ba introduced support for apostrophes. The problem is, that now genitive forms of a noun are detected as a single word.

e.g.:
```Build upon Python's asycio library.```
This would detect the words `Python's` which of course is not in any word list. `Python` is.

This currently breaks a lot of my sphinx spell checks :/

Refs #93 #94

**Comment by rfk** [comment]
Thanks @codingjoe, and sorry for the bustage. I'm not 100% sure how to proceed here because in my initial tests this seemed to work OK, e.g:

```
>>> d = enchant.Dict()
>>> d.check("Python's")
True
>>> d.check(u"Python\u2019s")
True
>>> d.provider
<Enchant: Aspell Provider>
>>>
```

Can you confirm whether this does or doesn't work for you if you execute it manually in a python shell?

**Comment by rfk** [comment]
Also, is this specific to the new support for `"u\2019"` typographic apostrophe, or do you also run into problems with ascii `"'`"?

**Comment by codingjoe** [comment]
@rfk thanks for replying so fast :)
Here is the information you requested.
```
Python 3.6.0 (default, Dec 29 2016, 00:54:51)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict()
>>> d.check("Python's")
True
>>> d.check(u"Python\u2019s")
False
>>> d.provider
<Enchant: Myspell Provider>
```

You can also check out, this build of one of my packages:
https://travis-ci.org/applegrew/django-select2/jobs/254719122

**Comment by rfk** [comment]
Thanks!  Looks like this might be specific to the Myspell provider, and possibly only on OSX.  I'll dig in further from here.

In the meantime, I'm going to backout this change and make a fresh release, since there's been a couple of reports of unexpected build bustage already :-(

**Comment by codingjoe** [comment]
@rfk just to be clear, since I didn't write that. My live shell example was from my Mac. The travis example is of course using Ubuntu.

**Comment by codingjoe** [comment]
And thanks! I appreciate this a lot :)

**Comment by mprpic** [comment]
I hit a similar issue where words define in a personal word list are not marked as correct if they include an `'s`:

```
In [1]: cat my_words.txt
asyncio

In [2]: import enchant

In [3]: d = enchant.Dict()

In [4]: d.check('asyncio')
Out[4]: False

In [5]: custom_dict = enchant.DictWithPWL('en_US', 'my_words.txt')

In [6]: custom_dict.check('asyncio')
Out[6]: True

In [7]: custom_dict.check("asyncio's")
Out[7]: False

In [8]: d.provider, custom_dict.provider
Out[8]: (<Enchant: Myspell Provider>, <Enchant: Myspell Provider>)
```

Is this the expected outcome?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
