### ISSUE TITLE
Provide rest/sphinx filter

### ISSUE THREAD

**Issue by mitar** [rfk/pyenchant#113]
I am using pylint to spell check comments, and it uses this package. I see that it uses `WikiWordFilter` but I think it would be great to also provide filter for rest/sphinx syntax. So if I use in my comment something like ` ``codeKeyword`` ` it would be filtered out and not detected as invalid word.

**Comment by rfk** [comment]
This is a great suggestion @mitar, thanks.  Unfortunately I don't find much time for this project these days so I'm not likely to get around to implementing it myself, but I'd be happy to offer help/suggestions/review to anyone who wants to take this on as a contribution.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
