### ISSUE TITLE
PWL: <word>'s checked false

### ISSUE THREAD

**Issue by nschloe** [rfk/pyenchant#115]
When using pyenchant with a personalized word list à la
```
$ cat names.txt
Wronski
```
I noticed that the words are checked correctly, but not with `'s`. For example:
```python
import enchant

d = enchant.DictWithPWL('en_US', 'names.txt')

d.check('Einstein')  # True
d.check('Einstein\'s')  # True

d.check('Wronski')  # True
d.check('Wronskian')  # True
d.check('Wronski\'s')  # False!
```
What's going wrong?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
