### ISSUE TITLE
Website not up to date

### ISSUE THREAD

**Issue by koebi** [rfk/pyenchant#120]
In the api-documentation on enchant.tokenize both on [pyhosted.org](https://pythonhosted.org/pyenchant/api/enchant.tokenize.html) and on [pyenchant.readthedocs.io](http://pyenchant.readthedocs.io/en/latest/api/enchant.tokenize.html) in the third example, there is a typo in `get_tokenier` (a `z` is missing), that was fixed in the source [three years ago](#52 ).

It would be nice if the documentation got updated, since I'd guess that that is not the only thing that has changed since then.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
