### ISSUE TITLE
Minor versions missing in pip

### ISSUE THREAD

**Issue by lucknerjb** [rfk/pyenchant#124]
Hello,

Is it possible to get pip updated with the minor/major versions since `1.6.6`?

Thanks!

**Comment by rfk** [comment]
Sorry for the delay replying here.  As far as I can tell the older versions should be present, e.g. here's the link for `1.6.11`:

  https://pypi.python.org/pypi/pyenchant/1.6.11

Can you say more about what you're expecting to be there but is not?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
