### ISSUE TITLE
Does not work with enchant >2.2

### ISSUE THREAD

**Issue by jebrosen** [rfk/pyenchant#125]
Enchant 2.2 made side-by-side installation of enchant 1.x and enchant 2.x easier, which included a rename of the pkgconfig files from `enchant` to `enchant-2`. Thus, errors such as this appear:
```
  File "/usr/lib/python2.7/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/usr/lib/python2.7/site-packages/enchant/_enchant.py", line 145, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
```

A fix that appears to work for me is adding `enchant-2` to the list of library names in _enchant.py: https://github.com/rfk/pyenchant/blob/d71ca73fd98b808a3cb199ddd185c092a61436bb/enchant/_enchant.py#L72-L76

This may not be a general solution, however, as I am not sure what this library's policy is regarding side-by-side installations and versions of the underlying C library.

**Comment by avkoval** [comment]
Agree. My project suddenly stoped building for me on Arch and I found that Arch developers solved it in same manner: 

https://git.archlinux.org/svntogit/community.git/tree/trunk/enchant-2.patch?h=packages/python-pyenchant

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
