### ISSUE TITLE
Fwd: [PATCH] Update for wxPython 3.0

### ISSUE THREAD

**Issue by hartwork** [rfk/pyenchant#132]
Hi!

I'm aware that `pyenchant` is marked as unmaintained.
For the record and any interested parties, I would like to link to a patch here that both Debian and Ubuntu are applying as of today:
https://salsa.debian.org/python-team/modules/pyenchant/blob/master/debian/patches/wxpython3.0.patch

Best, Sebastian

**Comment by dmerejkowsky** [comment]
Thanks for the patch! I've included in the master branch.

**Comment by dmerejkowsky** [comment]
Closed by commit: 4164049
