### ISSUE TITLE
English dictionary contains non-English words

### ISSUE THREAD

**Issue by Nick-Morgan** [rfk/pyenchant#133]
```

en_dict = enchant.Dict('en')
en_dict.check('Q')
True
en_dict.check('X')
True
en_dict.check('AA')
True
en_dict.check('AC')
True

```

It seems as if every single-letter string is considered to be an "English word", as are some two-letter strings. Why are these considered English words? As of now the only solution I can think of is creating a separate "blacklist" of words to override as a non-English word, but I am wondering if there is a more elegant way to accomplish this, or if there is support in pyEnchant for fine-tuning issues like this.

**Comment by dmerejkowsky** [comment]
There's an API for that:

```python
en_dict = enchant.Dict('en')
en_dict.check('Q')
True
en_dict.remove('Q')
en_dict.check('Q')
False
```

Note that you can use `remove_from_session` if you don't want the change to be permanent.
