### ISSUE TITLE
Dropping Python2 support

### ISSUE THREAD

**Issue by dmerejkowsky** [rfk/pyenchant#143]
Hi everyone,

I'm opening this issue so we can discuss whether we want to continue Python2 support or not.

Python2 is EOL starting 2020, so if you have a strong reason to use `pyenchant` with Python2, let us know by commenting below.

**Comment by rfk** [comment]
👍 to dropping py2 support FWIW; the old versions of the package will remaining available and working and I don't think they contain any showstopper bugs. It may be worth doing a major version number bump to reinforce the change.

**Comment by dmerejkowsky** [comment]
Duly noted. Thanks :)

**Comment by dmerejkowsky** [comment]
It's been two weeks, let's drop Python2
