### ISSUE TITLE
URLFilter does not match urls enclodes in <...>

### ISSUE THREAD

**Issue by htgoebel** [rfk/pyenchant#18]
URLs like `<http://www.gnu.org/licenses/>` are not recognized as URLs since they start with a angled bracket. Using  angled brackets arround URLs is recommended in http://www.w3.org/Addressing/URL/5.1_Wrappers.html.

Solution: Simply change the pattern into

```
    _pattern = re.compile(r"^([a-zA-z]+:\/\/[^\s].*"
                          "|"
                          r"<[a-zA-z]+:\/\/[^\s].*>)")
```

Draw-back: This will match this syntax in HTML, too. So a new `URLFilterWithBrackets` may be suited better.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
