### ISSUE TITLE
enchant.Dict("he").check always True

### ISSUE THREAD

**Issue by chao-mu** [rfk/pyenchant#26]
I have noticed a bug in the latest stable and github code. I am using hspell as a back end for Hebrew spell checking. All spell checks against it are returning True. See below.

> > > import enchant
> > > enchant.Dict("he").check("fo#$#4o")
> > > True

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
