### ISSUE TITLE
win32_data_files() should not include iconv, intl, libglib and libgmodule (?)

### ISSUE THREAD

**Issue by rimas-kudelis** [rfk/pyenchant#44]
In https://github.com/rfk/pyenchant/blob/master/enchant/utils.py#L334, there's currenty this piece of code:

        for prefix in ("iconv","intl","libglib","libgmodule"):
            if dll.startswith(prefix):
                break
        else:
            continue
        dataFiles[0][1].append(os.path.join(mainDir,dll))

From my understanding, this for cycle is currently non-functional. While I assume it's supposed to skip the four dll files and not add them to the data file list, it does nothing. If my assumption about the intention of this piece of code is correct, then here's a possible fix which makes it work:

        for prefix in ("iconv","intl","libglib","libgmodule"):
            if dll.startswith(prefix):
                skip = True
                break
            else:
                continue
        if not skip:
            dataFiles[0][1].append(os.path.join(mainDir,dll))

By the way, in lines 327-330 above this, libenchant.dll (or libenchant-1.dll) is being added to the list manually, but this `for` cycle adds that library anyway, making lines 327-330 unnecessary.

**Comment by rfk** [comment]
Thanks for pointing this out; after several years (!) I've gone ahead and simplified the loop to be more obvious about what it's doing:

  https://github.com/rfk/pyenchant/commit/fe8eafc15c4ba13660b2be45db314098cf252698
