### ISSUE TITLE
Python enchant dictionary exist but not working

### ISSUE THREAD

**Issue by boje** [rfk/pyenchant#50]
I am using Python2.7 and trying to get enchant or aspell to come with some Danish spelling suggestions. The same goes for Norwegian and Swedish. I am using OS X Yosemite

I downloaded the `brew install aspell --with-lang-da` and that seems to work, because the dictionary seems to exist.

``` python
import enchant

print enchant.list_languages() #['da', 'en', 'en_CA', 'en_GB', 'en_US']
print enchant.list_dicts() #[('da', <Enchant: Aspell Provider>), ('en', <Enchant: Aspell Provider>), ('en_CA', <Enchant: Aspell Provider>), ('en_GB', <Enchant: Aspell Provider>), ('en_US', <Enchant: Aspell Provider>)]

d = enchant.request_dict("da")
print(d.suggest("motorcyke"))

d = enchant.Dict("da")
print(d.suggest("motorcyke"))
```

The problem is that no suggestion are showing up. It is like the dictionary exist but is empty.

Thanks...

**Comment by rfk** [comment]
Whoops, sorry to leave this sitting unanswered for so long.  Do the dictionaries work if you call `check()` on a correctly-spelled word?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
