### ISSUE TITLE
Making correction suggestions from CmdLineChecker is tricky for us humans

### ISSUE THREAD

**Issue by pjmcdermott** [rfk/pyenchant#51]
I've just got started using pyenchant for my application in less than an hour, which is always a good sign. But I've gotta say: making the input for spelling suggestions zero-based is always going to be tricky for mere humans...

Anyone concur that to select the first suggestion in the list one should type '1', not '0'?

**Comment by rfk** [comment]
Yes, I concur :-)

That class really started out as an example app rather than anything  hoping for broad human usage, but I'd happily accept patches to make it more user-friendly.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
