### ISSUE TITLE
pyenchant not working with self-compiled enchant

### ISSUE THREAD

**Issue by lupussy** [rfk/pyenchant#53]
I'm using win7-64bit. Trying to use pyenchant 1.6.6 under WinPython-64bit I compiled enchant 1.6.0 with TDM-GCC-64 and copied the 3 dlls (libenchant-1.dll, libenchant_ispell.dll and libenchant_myspell.dll) into the proper folders (enchant/ or enchant/lib/enchant/). But using pyenchant I got an „Dict-not-found-error“. 
The same error message occured after compiling enchant with TDM-GCC-32 for Python-32bit.
What is going wrong?
Wolfgang

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
