### ISSUE TITLE
TypeError at shutdown

### ISSUE THREAD

**Issue by brbsix** [rfk/pyenchant#55]
I use pylint, which uses pyenchant. After pylint does its thing, pyenchant spits out an exception. This doesn't seem to happen linting every file, but it happens frequently.

Here is the exception:

    Exception ignored in: <bound method Broker.__del__ of <enchant.Broker object at 0x7f811afaad68>>
    Traceback (most recent call last):
      File "/home/USER/.local/lib/python3.4/site-packages/enchant/__init__.py", line 244, in __del__
      File "/home/USER/.local/lib/python3.4/site-packages/enchant/__init__.py", line 273, in _free
    TypeError: 'NoneType' object is not callable

As evident by the exception, the error seems to be occurring in the *Broker object destructor* `__del__()`. It looks like maybe the Broker class is setting self._free to None and then trying to execute it like self._free(), but I'm not certain. The *Dict object destructor* may also be vulnerable to the same sort of thing, as it runs self._free() in a try block with `except AttributeError` but does not catch `TypeError`. Anyways, I'm not familiar with pyenchant and whether that is likely to occur in the Dict class, so I won't add it.

I will submit a pull request to fix the error that I've been getting. If you think the same thing could occur in the Dict class then you may want to fix `__del__()` there too.

Update
----------
See pull request #56.

**Comment by rfk** [comment]
Thanks @brbsix, what version of python are you using?  I remember there being some verion-specific behaviour in the shutdown sequence that we need to be careful of.

**Comment by brbsix** [comment]
The Python version is sorta displayed in the exception, it is **Python 3.4.0**. I tested out `pyenchant` *v1.6.6* avail via PyPi and also a bdist_wheel built from the latest sources.

I haven't used pyenchant with __Python 2.7.*__ in a while but I seem to recall similar behavior. I really only normally interact (indirectly) with `pyenchant` via `pylint`. `pylint` can be installed with pip2 and pip3 at the same time, but there can only be one `~/.local/bin/pylint` executable, which happens to be the one for Python 3 on my system. I should be able to up a venv pretty quick and confirm the issue exists on Python 2 as well

**Comment by rfk** [comment]
Fixed in https://github.com/rfk/pyenchant/pull/56
