### ISSUE TITLE
OSX - wheel package for macosx_10_9_x86_64

### ISSUE THREAD

**Issue by matysek** [rfk/pyenchant#57]
On PYPI exists only 32bit .whl file (macosx_10_9_intel). Since OSX is 64bit these days, could be created 64bit .whl file for OSX?

**Comment by rfk** [comment]
I think I've figured out the necessary build stuff for this, it will be included in the next release.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
