### ISSUE TITLE
Windows import side effects

### ISSUE THREAD

**Issue by jim-easterbrook** [rfk/pyenchant#61]
I'm having difficulty using PyEnchant with PyGObject (https://wiki.gnome.org/Projects/PyGObject) on Windows 7. I'm using the WinPython (http://winpython.github.io/) portable distribution.

If I import enchant before PyGObject, the latter fails:
```
C:\Users\Jim\Documents\GitHub\Photini>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\gi\__init__.py", line 42, in <module>
    from . import _gi
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```

If I import gi first then enchant generates access violation errors:
```
C:\Users\Jim\Documents\GitHub\Photini>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> import enchant
>>> d = enchant.Dict()
>>> d.suggest('fred')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\enchant\__init__.py", line 651, in suggest
    suggs = _e.dict_suggest(self._this,word.encode())
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\enchant\_enchant.py", line 258, in dict_suggest
    suggs_c = dict_suggest1(dict,word,len(word),numSuggsP)
OSError: exception: access violation reading 0x561E097F
>>>
```

I've had a look at the import code in both PyEnchant and PyGObject and I'm unable to see how either is upsetting the other. I'm no expert in DLL importing though.

[PS I get similar results with Python 2.7]

**Comment by jim-easterbrook** [comment]
I've now tried an alternative GObject Python wrapper - pgi (https://pypi.python.org/pypi/pgi). I get similar problems - importing PyEnchant has a side effect that breaks import of GObject:
```
C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> import pgi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\__init__.py", line 10, in <module>
    from .importer import require_version, get_required_version
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\importer.py", line 12, in <module>
    from .clib.gir import GIRepository, GIError
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\clib\gir\__init__.py", line 9, in <module>
    from .gibaseinfo import GIInfoType, GIBaseInfo, GIAttributeIter
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\clib\gir\gibaseinfo.py", line 12, in <module>
    from .gitypelib import GITypelib
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\clib\gir\gitypelib.py", line 16, in <module>
    _gir = find_library("girepository-1.0")
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\site-packages\pgi\clib\_utils.py", line 99, in find_library
    _internal[name] = cdll.LoadLibrary(_so_mapping[name])
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Jim\Documents\GitHub\Photini\src\windows\WinPython\python-3.4.3
\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
>>>
```

**Comment by jim-easterbrook** [comment]
I think I may have found (part of) the answer. PyGObject and PyEnchant both include their own versions of `libglib-2.0-0.dll` and `libgmodule-2.0-0.dll`. Despite having the same names they have very different sizes, so are clearly not the same files!
As a Windows numpty I have no idea how to sort this out.

**Comment by rfk** [comment]
The ones that enchant bundles are very old pre-compiled glib binaries.  It may be possible to delete them and replace them with the ones from PyGObject, but I'm not sure.  Unfortunately I no longer have my windows dev environment set up so I can't dig into this at the moment :-(

**Comment by jim-easterbrook** [comment]
Thanks. I just tried that - the ones from PyGObject don't work with PyEnchant. I'm getting similar "procedure could not be found" errors but without importing `gi`.
Spell checking is an optional feature of my application, so Windows users will have to go without. Thanks for your help.

**Comment by jim-easterbrook** [comment]
Update - one of the PyGObject installer options installs a copy of `libenchant-1.dll`. Copying this, and the two glib DLLs, to the (py)enchant package directory yields a working installation using the same DLLs as PyGObject and causing no conflicts.
I've learnt more than I ever wanted to know about DLL Hell today.

**Comment by jim-easterbrook** [comment]
PS I've now found a way to make PyEnchant use PyGObject's DLLs without having to copy anything (which could cause permissions problems). Here's a code snippet for anyone else who runs in to similar problems:
```
if sys.platform == 'win32':
    # disable PyEnchant's forced use of its bundled DLLs
    sys.platform = 'win32x'
    # add gnome DLL location to PATH
    for name in site.getsitepackages():
        gnome_path = os.path.join(name, 'gnome')
        if os.path.isdir(gnome_path):
            os.environ['PATH'] = gnome_path + ';' + os.environ['PATH']
            break
import enchant
if sys.platform == 'win32x':
    # reset sys.platform
    sys.platform = 'win32'
    # using PyGObject's copy of libenchant means it won't find the
    # dictionaries installed with PyEnchant
    for name in site.getsitepackages():
        dict_path = os.path.join(name, 'enchant', 'share', 'enchant', 'myspell')
        if os.path.isdir(dict_path):
            enchant.set_param('enchant.myspell.dictionary.path', dict_path)
            break
```

**Comment by rfk** [comment]
>     # disable PyEnchant's forced use of its bundled DLLs

@jim-easterbrook thanks for digging into this.  I'd like to find a way to make it work better by default.  Would it work if you *deleted* the bundled DLLs that ship with pyenchant so that it doesn't try to use them, and added the `os.environ['PATH'] = gnome_path + ';' + os.environ['PATH']` trick shown above so that it can instead find the ones installed by PyGObject?

**Comment by jim-easterbrook** [comment]
I've just tried this and it works, although I still need to set the dictionary path as the PyGObject installation knows nothing of the dictionaries installed with pyenchant.
