### ISSUE TITLE
Remove all words in personal word lists

### ISSUE THREAD

**Issue by chenlianMT** [rfk/pyenchant#64]
I accidentally add words into this, and I forgot what I added. Is there a way to remove all words in this list? I tried to uninstall pyenchant and reinstall, but seems the personal word list file is not deleted while uninstalling.

**Comment by rfk** [comment]
I don't think there's a public function exposed that will do this, you may have to locate the file and delete it or remove words by hand.  I can try to suggest where to look for the file, what platform are you on?

**Comment by chenlianMT** [comment]
Thank you! I'm on OS X

**Comment by rfk** [comment]
For me the pwl files are in my home directory at /Users/rfk/.config/enchant/

**Comment by chenlianMT** [comment]
Great! I found it! By the way do you know which file should I delete? Cause all I found is ```en_GB.dic en_GB.exc en_UK.dic en_UK.exc en_US.dic en_US.exc```. Should I delete all of these and uninstall enchant and then reinstall?

**Comment by chenlianMT** [comment]
Well, I guess this folder is not the right folder containing personal dictionary list. Cause after I delete this whole folder, and rerun Dict('en_US').check('fdsafdsa'), it's still saying 'True'. After this when I looked into this configure folder, this deleted folder is regenerated.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
