### ISSUE TITLE
pyenchant lib isn't thread safe

### ISSUE THREAD

**Issue by stretch4x4** [rfk/pyenchant#66]
We were experiencing segmentation faults in our Django application, and we found the source of them to be in the pyenchant library.

When we put a thread lock around the code that called pyenchant the segmentation faults stopped.

![pyenchant lock](https://cloud.githubusercontent.com/assets/12271094/11832330/63dd794a-a40b-11e5-8083-18ee1d91e971.PNG)

It would be great if this was included in the library, to prevent others having this issue.

Cheers

**Comment by rfk** [comment]
Thanks for the feedback, we should definitely make this work by default.  Ideally we could depend on the GIL for this protection, but I can't see a way to tell a ctypes CDLL to hang onto the GIL during execution.

**Comment by stretch4x4** [comment]
No worries,
Yeah not very familiar with C libraries so can't really help you on that bit.
Thanks for taking a look.

**Comment by jim-easterbrook** [comment]
I think hanging on to the GIL would not be the right approach. It would prevent other Python threads from running while the CDLL is busy, potentially slowing down GUIs and so on which are nothing to do with the Enchant functions.
Do we know if Enchant itself is not threadsafe or if it's one or more of the backends that are a problem? Is this actually an Enchant bug?

**Comment by stretch4x4** [comment]
I think it must be enchant itself as we aren't using a specific backend, we are just loading our custom dic files straight into a personal word list.
This is the code that we have had to put the lock on and this seems to solve our issue:
```python
checker = SpellChecker(PersonalWordListWithDict(
            tag=None,
            pwl=dictionary_path),
            text=" ".join(body["params"]["words"])
        )
```

**Comment by rfk** [comment]
@stretch4x4 if you're still interested in digging into this, it would be great to try to narrow down the source of the thread-unsafety.  I wonder if it's e.g. specific to the code that does the suggestion-finding, and if putting a lock around just `enchant/_enchant.py:dict_suggest` rather than around all use of enchant would be sufficient.

**Comment by stretch4x4** [comment]
Happy to try and take a look at that, might have a bit more time towards the end of the week if I don't forget :)

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
