### ISSUE TITLE
"The 'enchant' C library was not found" during import after installation with pip

### ISSUE THREAD

**Issue by mbramson** [rfk/pyenchant#70]
Using Windows 7, Python 2.7.10 via MiniConda. (confirmed this happens in 2.7.11 as well)

```
$ pip install enchant
```

```
Collecting pyenchant
  Using cached pyenchant-1.6.6-py2.py3-none-any.whl
Installing collected packages: pyenchant
Successfully installed pyenchant-1.6.6
```

pip is verison 7.1.2

Try to import enchant and this is the result:

```
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Miniconda\lib\site-packages\enchant\__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "c:\Miniconda\lib\site-packages\enchant\_enchant.py", line 143, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
```

**Comment by ARezaK** [comment]
Had the same problem when using 64 bit python.

**Comment by ARezaK** [comment]
https://github.com/rfk/pyenchant/issues/42

**Comment by DavidAwad** [comment]
can repeat this when testing using pyenchant on travis CI. 

See failed builds: https://travis-ci.org/DavidAwad/spelltest/builds/194984935

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
