### ISSUE TITLE
unable to find new dictionary

### ISSUE THREAD

**Issue by donnut** [rfk/pyenchant#75]
I've create a new dictionary following the steps in [5.4](http://aspell.net/0.50-doc/man-html/5_Working.html). The dictionary is named `nl_NL-hist.rws` and the file `nl_NL-hist.multi` points to it. The new dict works if it is called on the command line like:

```
aspell check --master=nl_NL-hist some_text.txt
```

Tried it in a python3 file:

```
import enchant
nl = enchant.Dict('nl_NL-hist')
nl.check('known_awkward_word') # False
```

It seems that enchant is unable to find the new dictionary. How can I solve this?

**Comment by donnut** [comment]
BTW
`print( enchant.list_dicts())` results in:
```
[('en', <Enchant: Aspell Provider>), ('en_CA', <Enchant: Aspell Provider>), ('en_GB', <Enchant: Aspell Provider>), ('en_US', <Enchant: Aspell Provider>), ('nl', <Enchant: Aspell Provider>), ('nl_NL', <Enchant: Aspell Provider>), ('he', <Enchant: Hspell Provider>)]
```

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
