### ISSUE TITLE
PyPi release

### ISSUE THREAD

**Issue by codingjoe** [rfk/pyenchant#82]
Hi @rfk 

Why hasn't there been a new PyPi release within 2 years. If I'm not mistaken you fixed plenty of bugs in the mean time that qualify for a new bugfix or minor release.

I think many people would appreciate a new release since the package doesn't work on MacOS.

Thanks,
Joe

**Comment by rfk** [comment]
Hi @codingjoe, thanks for reaching out.  The simple (and slightly sad) answer is, I lost my original build environment for this code during a machine upgrade years ago, and I haven't found time to set it all back up.  The folks over in issue #45 are working on helping out with building a new release, hopefully we can get one soon.

**Comment by codingjoe** [comment]
@rfk oh, I'm sorry to hear that. If I'm reading this correctly this is only about a wheel release. Source releases would be just fine for me ;)
