### ISSUE TITLE
'ascii' codec can't decode byte 0xce - CmdLineChecker (greek)

### ISSUE THREAD

**Issue by vaggelisk** [rfk/pyenchant#83]
I try to run this script in python to check a text in greek,
and what I get back is an error because "'ascii' codec can't decode
 byte 0xce". When I run the same script but with an english text  in
output42, the CmdLineChecker runs perfectly, but when I put 
`SpellChecker("gr")` or `el` or `el_GR`, there is this problem.
Could anyone help me?

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import enchant.checker
from enchant.checker.CmdLineChecker import CmdLineChecker

chkr = enchant.checker.SpellChecker("gr")

targ = open( "output42.txt", "r")
text = targ.read()
targ.close()

chkr.set_text(text)
cmdln = CmdLineChecker()
cmdln.set_checker(chkr)

cmdln.run()
```

> python ekdos2.py
>  Traceback (most recent call last):
>   File "ekdos2.py", line 25, in <module>
>     cmdln.run()
>   File "/usr/local/lib/python2.7/dist-packages/enchant/checker/CmdLineChecker.py", line 70, in run
>     printf(["ERROR:", err.word.encode('utf8')])
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 0: ordinal not in range(128)

Here is some greek text, if anyone wants to try...

> που ακολουθούν ο γιατρός όχι µόνο βρίσκει νε-
> κρούς αρουραίους σε ολόκληρη την πόλη αλλά.
> σαν γιατρός, έρχεται αντιµέτωπος µε έναν

**Comment by rfk** [comment]
Hi @vaggelisk, what encoding is your input file "output42.txt" stored in?  At the part where you do `test = targ.read()` you may need to explicitly decode it into a unicode string before passing it to the spellchecker.

**Comment by vaggelisk** [comment]
> output42.txt: text/plain; charset=utf-8

Every letter counts for 2 in python function _.find("sth")_

The problem solved, when I threw away the `encode()` in line 71  of CmdLineChecker.
So, instead of:
`   printf([ "ERROR: ", err.word.encode()])`
I put:
`   printf([ "ERROR: ", err.word]) `

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
