### ISSUE TITLE
v1.6.7 at PyPI

### ISSUE THREAD

**Issue by jwilk** [rfk/pyenchant#84]
I see there's a tag for v1.6.7 in the git repo, but the last version at PyPI is still 1.6.6.
Could you upload v1.6.7 to PyPI?

**Comment by jsma** [comment]
Are there any issues blocking a new release that we can help with? Thanks!

**Comment by rfk** [comment]
Sorry for the delay here, no issues apart from just finding the time to sit down with it - I'll try to steal 20mins or so on the weekend and finalize all the details

**Comment by rfk** [comment]
I've released version 1.6.7: https://pypi.python.org/pypi/pyenchant/1.6.7

The build scripts here are pretty rusty, please let me know if you notice any bustage.
