### ISSUE TITLE
Can't find installed enchant library

### ISSUE THREAD

**Issue by jhamrick** [rfk/pyenchant#87]
I am on OS X 10.10 and I have enchant installed via homebrew. However, when I try to install pyenchant, I get:

```
$ pip install pyenchant --upgrade
Collecting pyenchant
  Using cached pyenchant-1.6.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/pip-build-2qt3pkh4/pyenchant/setup.py", line 210, in <module>
        import enchant
      File "/private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/pip-build-2qt3pkh4/pyenchant/enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "/private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/pip-build-2qt3pkh4/pyenchant/enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4d/_j28yxlj4bn9p6zlgn4gr2m40000gn/T/pip-build-2qt3pkh4/pyenchant/
```

Unfortunately there are no pre-built binary wheels on PyPI for MacOS, and the only ones that are availble [on the downloads page](http://pythonhosted.org/pyenchant/download.html) are for the previous version of pyenchant, which don't work because of #45.

Any chance there could be a wheel built for OS X too, and/or whatever issue there is with finding enchant installed via homebrew fixed? It definitely used to be able to find enchant installed via homebrew, so I'm not sure what changed.

**Comment by jhamrick** [comment]
Ah, just saw #85, which would partially address this. I would still think it should be able to work with having enchant installed via homebrew, though?

**Comment by rfk** [comment]
Hi @jhamrick, indeed it *should* work with enchant installed via homebrew, I'm not sure what's changed here in the latest version.  I'm about to publish v1.6.8 with a binary wheel for OSX which should at least get things back up and running for you, but I'm at a loss to explain why it would stop working with homebrewed enchant lib :-(

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
