### ISSUE TITLE
DictWithPWL requires pwl file to be in writable state to open?

### ISSUE THREAD

**Issue by dostjh** [rfk/pyenchant#91]
When using a source controlled pwl, it appears that I have to adjust the read-only state on the file to writable before DictWithPWL will accept it as a valid word list.

```
Traceback (most recent call last):
  File "C:\StRAP\SpellChecker\SpellChecker.py", line 30, in <module>
    dictionaries = enchant.DictWithPWL("en_US",pwl="words_include.txt",pel="words_exclude.txt")
  File "C:\Users\jdost\AppData\Local\Programs\Python\Python35-32\lib\site-packages\enchant\__init__.py", line 822, in __init__
    self.pwl = self._broker.request_pwl_dict(pwl)
  File "C:\Users\jdost\AppData\Local\Programs\Python\Python35-32\lib\site-packages\enchant\__init__.py", line 330, in request_pwl_dict
    self._raise_error(eStr % (pwl,))
  File "C:\Users\jdost\AppData\Local\Programs\Python\Python35-32\lib\site-packages\enchant\__init__.py", line 259, in _raise_error
    raise eclass(EnchantStr("").decode(err))
enchant.errors.Error: Couldn't open personal wordlist 'words_include.txt'
```
I can bypass this error by changing the file state to writable, but I'd prefer to not have to do this.

**Comment by rfk** [comment]
Thanks for the report.  This appears to be caused by the underlying enchant library, which AFAICT opens the file in append mode in order to force its creation when it doesn't exist:

  https://github.com/AbiWord/enchant/blob/master/src/pwl.c#L267

At first glance I don't think there's much we can do about this at the PyEnchant level, part from try to get it fixed upstream.

**Comment by bolind** [comment]
That would be very nice to have fixed. I have a (not all that uncommon or unreasonable IMHO) scenario where I want to maintain a read-only PWL for a number of users, and this bug is blocking that.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
