### ISSUE TITLE
Why has pyenchant no Windows 64-bit support?

### ISSUE THREAD

**Issue by Paebbels** [rfk/pyenchant#92]
There is no wheel file for Windows 64 bit operating systems.

**Comment by GadgetSteve** [comment]
PyEnchant works fine on the Windows 64 bit operating system but binaries and wheels are only provided for 32 bit Python not 64 bit at the moment.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
