### ISSUE TITLE
getting sentence context with CmdLine Checker?

### ISSUE THREAD

**Issue by Ratatam123** [rfk/pyenchant#95]
Hi,

does anyone know whether there is a possibility to show the sentence context when running the spell checker over the command line? 
for example:
...
cmd_checker = CmdLineChecker()    
chunker.set_text(text_string)
cmd_checker.set_checker(chunker)
cmd_checker.run()

**Comment by rfk** [comment]
Such functionality is not currently supported.  It would be a neat addition!  Unfortunatley I don't really have time to hack on PyEnchant much these days so I'm unlikely to add it myself.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
