### ISSUE TITLE
Windows installer checks wrong registry key for python detection

### ISSUE THREAD

**Issue by mstammberger** [rfk/pyenchant#96]
The windows installer refuses the installation if it did not find a python installation in the registry.
It seems that it checks only the registry key HKEY_CURRENT_USER\Software\Python.

But if Python is installed for "all users" this key doesn't exist!
Instead the required data then is stored at HKEY_LOCAL_MACHINE\SOFTWARE\Python

As a workaround I exported the registry entries from HKEY_LOCAL_MACHINE\SOFTWARE\Python into a .reg file. Then adapted the file by replacing all occurrences of HKEY_LOCAL_MACHINE\SOFTWARE by HKEY_CURRENT_USER\Software and then imported it back to the registry.
Then the installer found the Python installation and allowed the installation of PyEnchant.

The installer should check both paths.

**Comment by rfk** [comment]
Thanks for the report @mstammberger.  I wonder if this is a bug in the version of python I used to make the binary installer.  There's no code in pyenchant itself that's responsible for this check, IIRC it's all just the default installer you get from `python setup.py bdist_wininst`.

**Comment by MandarJKulkarni** [comment]
I too faced the same issue. The only solution was to add the registry entries under HKEY_CURRENT_USER as mentioned by mstammberger

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
