### ISSUE TITLE
pyenchant not reading from ENCHANT_USER_PATH_EXTENSION

### ISSUE THREAD

**Issue by korser** [rfk/pyenchant#99]
I unfortunately have a non-standard installation for aspell and enchant. I need to copy libenchant_aspell.so and aspell dictionary inside my  ENCHANT_USER_PATH_EXTENSION (~/.enchant on linux).

When I use enchant from the command line it's loading aspell and the dictionaries correctly. For example this command returns:

```
$ echo tablee | enchant -a

@(#) International Ispell Version 3.1.20 (but really Enchant 1.6.0)
& tablee 30 0: tab lee, tab-lee, table, tableau, tabla, tabled, tables, tablet, Tarbell, dabbler, tabular, abler, dabble, stabler, tale, tubule, able, table's, taller, stable, Gable, Mable, cable, doable, fable, gable, sable, Talley, tablas, tabla's
```

Also enchant-lsmod correctly returns aspell
`aspell (Aspell Provider)
`
In pyenchant this is what I get when I try to list the dictionaries available:

```
>>> import enchant
>>> enchant.list_dicts()
[]
```

Is there any specific configurations that needs to be done to pyenchant via set_param or ENCHANT_USER_PATH_EXTENSION is just not supported?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
